# Generated by Django 3.0.5 on 2020-07-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20, null=True)),
                ('apellidos', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20, null=True)),
                ('marca', models.CharField(max_length=20, null=True)),
                ('precio', models.IntegerField(null=True)),
                ('stock', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20, null=True)),
                ('apellidos', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
