# Generated by Django 2.2.15 on 2020-09-11 17:18

from django.db import migrations, models
import djongo.models.fields
import tienda.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=10)),
                ('Tecnico', djongo.models.fields.ArrayField(model_container=tienda.models.Tecnico, model_form_class=tienda.models.TecnicoForm)),
                ('Departamento', djongo.models.fields.ArrayField(model_container=djongo.models.fields.ArrayField(model_container=tienda.models.Departamento), model_form_class=tienda.models.DepartamentoForm)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=10)),
                ('nombre', models.IntegerField()),
                ('apellidos', models.IntegerField()),
                ('contraseña', models.CharField(max_length=1000)),
                ('correo', models.CharField(max_length=1000)),
                ('reclamo', djongo.models.fields.ArrayField(model_container=tienda.models.Reclamo, model_form_class=tienda.models.ReclamoForm)),
                ('servicio', djongo.models.fields.ArrayField(model_container=tienda.models.Servicio, model_form_class=tienda.models.ServicioForm)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=10)),
                ('direcion', models.CharField(max_length=1000)),
                ('capacidad', models.IntegerField()),
                ('Inventario', djongo.models.fields.EmbeddedField(model_container=tienda.models.Inventario, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=1000)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_nacimiento', models.DateField()),
                ('Reclamo', djongo.models.fields.ArrayField(model_container=tienda.models.Reclamo, model_form_class=tienda.models.ReclamoForm)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=10)),
                ('tipo_reclamo', models.CharField(max_length=1000)),
                ('fecha_reclamo', models.DateField()),
                ('descripcion', models.CharField(max_length=1000)),
                ('estado', models.IntegerField()),
                ('prioridad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=10)),
                ('tipo_servicio', models.CharField(max_length=1000)),
                ('costo', models.FloatField()),
                ('Estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=10)),
                ('nombre', models.IntegerField()),
                ('apellidos', models.IntegerField()),
                ('fecha_ingreso', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('servicio', djongo.models.fields.ArrayField(model_container=tienda.models.Servicio, model_form_class=tienda.models.ServicioForm)),
                ('informe', djongo.models.fields.EmbeddedField(model_container=tienda.models.Informe, null=True)),
            ],
        ),
    ]
